// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"ja_JP": &dictionary{index: ja_JPIndex, data: ja_JPData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Additional Commands:":             20,
	"Additional help topics:":          23,
	"Aliases:":                         17,
	"Available Commands:":              19,
	"CLI for Kinto scripts and tools.": 0,
	"Examples:":                        18,
	"Flags:":                           21,
	"Global Flags:":                    22,
	"Help about any command":           13,
	"Help provides help for any command in the application.\nSimply type %s help [path to command] for full details.":                                                     14,
	"Kinto CLI or ktcli is a command line interface for employees at Kinto Technologies, allowing easy access to the multiple tools and scripts developped by our teams.": 1,
	"Prints logs to stdout.":         3,
	"Prints the help message.":       5,
	"Prints the version of the CLI.": 4,
	"Select the language to use":     10,
	"Set global configurations for ktcli. Updates the local configuration file with the selected option.": 7,
	"Set global configurations.":           6,
	"Set the language to use for the CLI.": 8,
	"Set the language to use for the CLI. Updates the local configuration file with the selected language. If no language is provided, the CLI will prompt you to select one.": 9,
	"Sets the log level to debug.":          2,
	"Unknown help topic %#q":                15,
	"Usage:":                                16,
	"Use":                                   24,
	"You selected: %s":                      11,
	"for more information about a command.": 25,
	"help for %s":                           12,
}

var en_GBIndex = []uint32{ // 27 elements
	0x00000000, 0x00000021, 0x000000c5, 0x000000e2,
	0x000000f9, 0x00000118, 0x00000131, 0x0000014c,
	0x000001b0, 0x000001d5, 0x0000027e, 0x00000299,
	0x000002ad, 0x000002bc, 0x000002d3, 0x00000345,
	0x0000035f, 0x00000366, 0x0000036f, 0x00000379,
	0x0000038d, 0x000003a2, 0x000003a9, 0x000003b7,
	0x000003cf, 0x000003d3, 0x000003f9,
} // Size: 132 bytes

const en_GBData string = "" + // Size: 1017 bytes
	"\x02CLI for Kinto scripts and tools.\x02Kinto CLI or ktcli is a command " +
	"line interface for employees at Kinto Technologies, allowing easy access" +
	" to the multiple tools and scripts developped by our teams.\x02Sets the " +
	"log level to debug.\x02Prints logs to stdout.\x02Prints the version of t" +
	"he CLI.\x02Prints the help message.\x02Set global configurations.\x02Set" +
	" global configurations for ktcli. Updates the local configuration file w" +
	"ith the selected option.\x02Set the language to use for the CLI.\x02Set " +
	"the language to use for the CLI. Updates the local configuration file wi" +
	"th the selected language. If no language is provided, the CLI will promp" +
	"t you to select one.\x02Select the language to use\x02You selected: %[1]" +
	"s\x02help for %[1]s\x02Help about any command\x02Help provides help for " +
	"any command in the application.\x0aSimply type %[1]s help [path to comma" +
	"nd] for full details.\x02Unknown help topic %#[1]q\x02Usage:\x02Aliases:" +
	"\x02Examples:\x02Available Commands:\x02Additional Commands:\x02Flags:" +
	"\x02Global Flags:\x02Additional help topics:\x02Use\x02for more informat" +
	"ion about a command."

var ja_JPIndex = []uint32{ // 27 elements
	0x00000000, 0x0000002d, 0x00000109, 0x0000013a,
	0x00000162, 0x0000018d, 0x000001b6, 0x000001de,
	0x00000262, 0x00000290, 0x00000361, 0x00000392,
	0x000003b0, 0x000003dd, 0x000003ff, 0x000004c6,
	0x000004ec, 0x000004fa, 0x0000050b, 0x00000510,
	0x0000052d, 0x00000547, 0x00000555, 0x00000572,
	0x00000595, 0x000005bd, 0x000005da,
} // Size: 132 bytes

const ja_JPData string = "" + // Size: 1498 bytes
	"\x02KintoのスクリプトとツールのCLI。\x02ktcliはKinto Technologiesの従業員のためのコマンドラインインターフ" +
	"ェイスで\x0a当社のチームによって開発された複数のツールやスクリプトに簡単にアクセスできます。\x02ログレベルをデバッグに設定する。" +
	"\x02標準出力にログを出力する。\x02CLIのバージョンを表示します。\x02helpメッセージを表示します。\x02グローバル設定を行いま" +
	"す。\x02ktcliのグローバル構成を設定します。選択したオプションでローカル設定ファイルを更新します。\x02CLIで使用する言語を設定" +
	"します。\x02CLIに使用する言語を設定する。選択した言語でローカル設定ファイルを更新します\x0a言語が指定されていない場合、CLIは言" +
	"語を選択するように要求します。\x02使用する言語を選択してください。\x02%[1]sを選択しました。\x02%[1]sの使用方法について" +
	"のヘルプ\x02コマンドに関するヘルプ\x02ヘルプはアプリケーションのどのコマンドに対してもヘルプを表示しま す。\x0a%[1]s he" +
	"lp [コマンドへのパス]と入力するだけで、詳細が表示されます。\x02不明なヘルプトピック %#[1]q\x02使用方法:\x02エイリアス:" +
	"\x02例:\x02利用可能なコマンド:\x02その他のコマンド:\x02フラッグ:\x02グローバルフラッグ:\x02その他のヘルプトピック:" +
	"\x02コマンドの詳細については、\x02 を使用して下さい。"

	// Total table size 2779 bytes (2KiB); checksum: 7D06E70E
