// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"ja_JP": &dictionary{index: ja_JPIndex, data: ja_JPData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"CLI for Kinto scripts and tools.": 2,
	"Kinto CLI or ktcli is a command line interface for employees at Kinto Technologies, allowing easy access to the multiple tools and scripts developped by our teams.": 3,
	"Prints logs to stdout.":       5,
	"Select the language to use":   0,
	"Sets the log level to debug.": 4,
	"You selected: %s":             1,
}

var en_GBIndex = []uint32{ // 7 elements
	0x00000000, 0x0000001b, 0x0000002f, 0x00000050,
	0x000000f4, 0x00000111, 0x00000128,
} // Size: 52 bytes

const en_GBData string = "" + // Size: 296 bytes
	"\x02Select the language to use\x02You selected: %[1]s\x02CLI for Kinto s" +
	"cripts and tools.\x02Kinto CLI or ktcli is a command line interface for " +
	"employees at Kinto Technologies, allowing easy access to the multiple to" +
	"ols and scripts developped by our teams.\x02Sets the log level to debug." +
	"\x02Prints logs to stdout."

var ja_JPIndex = []uint32{ // 7 elements
	0x00000000, 0x00000031, 0x0000004f, 0x0000007c,
	0x0000015a, 0x0000018b, 0x000001b3,
} // Size: 52 bytes

const ja_JPData string = "" + // Size: 435 bytes
	"\x02使用する言語を選択してください。\x02%[1]sを選択しました。\x02KintoのスクリプトとツールのCLI。\x02ktcliはK" +
	"into Technologiesの従業員のためのコマンドラインインターフェイスで、当社のチームによって開発された複数のツールやスクリプトに簡単" +
	"にアクセスできます。\x02ログレベルをデバッグに設定する。\x02標準出力にログを出力する。"

	// Total table size 835 bytes (0KiB); checksum: 35A30175
